### ISSUE TITLE
Please allow title to be changed.

### ISSUE THREAD

**Issue by dimitko** [peleteiro/progressbar#16]
Hey, and thanks for your awesome little gem. Does wonders for me in several CLI tools. Appreciate your effort.

I have a little nitpick here. I completed a script that downloads and re-uploads files to S3 / Google Cloud Storage / Rackspace / etc. and currently I create a new `ProgressBar` for every file because I'm using titles like "1 / N", then "2 / N" etc. until the end of the script.

What I'd really appreciate is to be able to change the title of the `ProgressBar`. So, when I am done with file 1, I can reset the object's position to zero and also change the title to show "file 2 / N". I want this because that way I won't be creating hundreds of `ProgressBar`s which are taking one line of text each. If your gem had that feature, I'd be able to show only one `ProgressBar` and constantly reset its position and change its title after the current step has been completed.

I suppose there are other ways to do this, but I thought to myself -- why not try make it an official feature.

Thanks for your work.

**Comment by peleteiro** [comment]
Progressbar will merge with [ruby-progressbar](https://github.com/jfelchner/ruby-progressbar) soon.
